import Head from 'next/head'
import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'
import './globals.css'

export const metadata = {
  title: 'Tech Masih',
  description: 'Generated by Tech Masih',
}
interface IProps{
children: React.ReactNode
}
export default function RootLayout({children}: IProps) {
  return (
    <html lang="en">
      <body
       suppressHydrationWarning={true}
       className='min-h-screen flex flex-col justify-center bg-[#1D1B3D] text-white'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
