import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'
import './globals.css'

export const metadata = {
  title: 'Tech Masih',
  description: 'Generated by Tech Masih',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen bg-[#1D1B3D] text-white'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
